import { test, expect } from '@playwright/test';
import { installApi, openDashboard, openIncident, operator, signIn } from './api-fixture';
import type { IncidentWorkflow, MapData } from '../types';

test('complete collections, severity ordering, filters and unknown event types', async ({ page }) => {
  const state = await installApi(page);
  state.data.incidents[0].type = 'unexpected_signal';
  await openDashboard(page);
  await expect(page.getByTestId('active-count')).toHaveText('5');
  await expect(page.locator('.incident-card').first()).toContainText('Obstruction at port entrance');
  await expect(page.locator('.incident-card')).toHaveCount(4);
  await page.getByRole('link', { name: 'View all incidents', exact: true }).click();
  await page.getByRole('button', { name: 'Filters', exact: true }).click();
  await expect(page.locator('.incident-card')).toHaveCount(5);
  await page.getByLabel('Severity', { exact: true }).selectOption('high');
  await expect(page.locator('.incident-card')).toHaveCount(1);
  await page.getByLabel('Severity', { exact: true }).selectOption('all');
  await page.getByLabel('Type', { exact: true }).selectOption('unexpected_signal');
  await expect(page.locator('.incident-card')).toHaveCount(1);
  const details = await openIncident(page, 'Slow traffic on Custom House Quay');
  await expect(details.getByText('Unexpected signal', { exact: true })).toBeVisible();
  await page.keyboard.press('Escape');
  await page.getByLabel('Type', { exact: true }).selectOption('all');
  await page.getByRole('group', { name: 'Incident status' }).getByRole('button', { name: 'Resolved', exact: true }).click();
  await expect(page.locator('.incident-card')).toHaveCount(1);
  await page.getByLabel('Search incidents').fill('no match');
  await expect(page.getByText('No incidents match these filters.')).toBeVisible();
  await page.getByRole('link', { name: 'Cameras', exact: true }).click();
  await expect(page.locator('.camera-card')).toHaveCount(6);
  await page.getByLabel('Search cameras').fill('DCU');
  await expect(page.locator('.camera-card')).toHaveCount(1);
  expect(state.pageErrors).toEqual([]);
});

test('co-located markers expose both camera and incident; selection and layers agree', async ({ page }) => {
  await installApi(page);
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await openDashboard(page);
  const marker = page.locator('.leaflet-marker-icon').filter({ has: page.locator('span', { hasText: /^2$/ }) });
  await expect(marker.first()).toBeVisible();
  await expect(page.locator('.leaflet-tile-loaded').first()).toBeVisible();
  await page.screenshot({ path: '../output/playwright/desktop-dashboard.png', fullPage: true });
  await page.locator('.leaflet-marker-icon[title^="Custom House Quay:"]').click();
  const popup = page.locator('.location-popup');
  await expect(popup.getByRole('button', { name: /Slow traffic/ })).toBeVisible();
  await expect(popup.getByRole('button', { name: /Eastbound/ })).toBeVisible();
  await popup.getByRole('button', { name: /Slow traffic/ }).click();
  await expect(page.getByRole('dialog', { name: 'Slow traffic on Custom House Quay' })).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.locator('.marker-selected')).toHaveCount(0);
  const mapPosition = await page.locator('.leaflet-map-pane').getAttribute('style');
  await page.getByRole('button', { name: 'Refresh data' }).click();
  await expect(page.getByRole('button', { name: 'Refresh data' })).toBeEnabled();
  await expect(page.locator('.leaflet-map-pane')).toHaveAttribute('style', mapPosition!);
  await page.getByRole('checkbox', { name: 'Incidents', exact: true }).uncheck();
  await expect(page.locator('.leaflet-marker-icon[title^="Custom House Quay:"]')).not.toHaveAttribute('title', /Slow traffic/);
  await page.getByRole('button', { name: 'Fit Dublin coverage' }).click();
  await expect(page.getByRole('link', { name: 'OpenStreetMap', exact: true })).toBeVisible();
});

test('camera history is newest first, newer observation previews and evidence navigation work', async ({ page }) => {
  await installApi(page);
  await openDashboard(page);
  await page.getByRole('button', { name: /Open camera Custom House/ }).click();
  let dialog = page.getByRole('dialog');
  await expect(dialog.getByText(/Newer observation/)).toBeVisible();
  await expect(dialog.locator('.observation-row').nth(1)).toContainText('demo-observation-quay');
  await expect(dialog.locator('.observation-row').nth(2)).toContainText('demo-observation-quay-1');
  await dialog.locator('.observation-row').nth(3).click();
  await expect(dialog.locator('.observation-row').nth(3)).toHaveAttribute('aria-pressed', 'true');
  await page.keyboard.press('Escape');
  dialog = await openIncident(page, 'Slow traffic on Custom House Quay');
  await dialog.getByRole('button', { name: 'Open camera evidence' }).click();
  dialog = page.getByRole('dialog', { name: /Custom House Quay · Eastbound/ });
  await expect(dialog.locator('.observation-row').nth(1)).toHaveAttribute('aria-pressed', 'true');
  await dialog.getByRole('button', { name: 'Back to incident' }).click();
  await expect(page.getByRole('dialog', { name: 'Slow traffic on Custom House Quay' })).toBeVisible();
});

test('login failure, success, logout and signed-out restrictions', async ({ page }) => {
  const state = await installApi(page);
  await openDashboard(page);
  const incident = await openIncident(page);
  await expect(incident.getByRole('button', { name: 'Resolve incident' })).toHaveCount(0);
  await page.keyboard.press('Escape');
  await signIn(page, 'bad-password');
  await expect(page.getByRole('dialog').getByRole('alert')).toHaveText('Email or password is incorrect.');
  const login = page.getByRole('dialog', { name: 'Operator sign in' });
  await login.getByLabel('Password', { exact: true }).fill('valid-password');
  await login.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Sign out' })).toBeVisible();
  await page.getByRole('button', { name: 'Sign out' }).click();
  await expect(page.getByRole('button', { name: 'Operator sign in' })).toBeVisible();
  expect(state.user).toBeNull();
  expect(await page.evaluate(() => Object.keys(sessionStorage))).not.toContain('token');
});

test('assignment, unassignment, acknowledgment and resolution update all views and survive source upserts', async ({ page }) => {
  const state = await installApi(page, { user: operator });
  await openDashboard(page);
  const dialog = await openIncident(page);
  await dialog.getByLabel('Assign operator').selectOption(operator.id);
  await expect(dialog.getByText('Change saved.', { exact: true })).toBeVisible();
  expect(state.workflows[0].acknowledged_at).toBeNull();
  await dialog.getByLabel('Assign operator').selectOption('');
  await expect(dialog.getByLabel('Assign operator')).toHaveValue('');
  await dialog.getByLabel('Assign operator').selectOption(operator.id);
  await expect(dialog.getByLabel('Assign operator')).toHaveValue(operator.id);
  await dialog.getByRole('button', { name: 'Acknowledge', exact: true }).click();
  await expect(dialog.getByRole('button', { name: 'Acknowledge', exact: true })).toBeDisabled();
  const acknowledgedAt = state.workflows[0].acknowledged_at;
  await dialog.getByRole('button', { name: 'Resolve incident' }).click();
  await expect(dialog.getByRole('button', { name: 'Resolved', exact: true })).toBeDisabled();
  expect(state.workflows[0].acknowledged_at).toBe(acknowledgedAt);
  await page.keyboard.press('Escape');
  await expect(page.getByTestId('active-count')).toHaveText('4');
  await expect(page.locator('.leaflet-marker-icon[title^="Dublin Port:"]')).not.toHaveAttribute('title', /Obstruction/);
  state.data.incidents.find((item) => item.id === 'demo-incident-port')!.title = 'Port obstruction updated by ingestion';
  await page.getByRole('button', { name: 'Refresh data' }).click();
  await expect(page.getByRole('button', { name: 'Refresh data' })).toBeEnabled();
  await expect(page.getByTestId('active-count')).toHaveText('4');
  await page.getByRole('link', { name: 'Incidents', exact: true }).click();
  await page.getByRole('button', { name: 'Filters', exact: true }).click();
  await page.getByRole('group', { name: 'Incident status' }).getByRole('button', { name: 'Resolved', exact: true }).click();
  await page.getByLabel('Assignee', { exact: true }).selectOption('me');
  await expect(page.locator('.incident-card')).toHaveCount(1);
  await expect(page.locator('.incident-card')).toContainText('Port obstruction updated by ingestion');
  await page.reload();
  await page.goto('/');
  await expect(page.getByTestId('active-count')).toHaveText('4');
});

test('failed saves and expired sessions never resolve locally', async ({ page }) => {
  const state = await installApi(page, { user: operator, saveError: 503 });
  await openDashboard(page);
  const dialog = await openIncident(page);
  await dialog.getByRole('button', { name: 'Resolve incident' }).click();
  await expect(dialog.getByRole('alert')).toContainText('Your change was not saved');
  await expect(dialog.getByRole('button', { name: 'Resolve incident' })).toBeEnabled();
  state.saveError = 401;
  state.user = null;
  await dialog.getByRole('button', { name: 'Resolve incident' }).click();
  await expect(dialog.getByRole('button', { name: 'Sign in to manage' })).toBeVisible();
  await expect(dialog.getByRole('alert')).toContainText('session has expired');
  expect(state.workflows).toEqual([]);
  await page.keyboard.press('Escape');
  await expect(page.getByTestId('active-count')).toHaveText('5');
});

test('an in-flight workflow read and a later stale read cannot undo a completed save', async ({ page }) => {
  const state = await installApi(page, { user: operator });
  await page.clock.install();
  await openDashboard(page);
  let release!: (value: IncidentWorkflow[]) => void;
  state.nextWorkflows = new Promise((resolve) => { release = resolve; });
  const reads = state.workflowReads;
  await page.getByRole('button', { name: 'Refresh data' }).click();
  await expect.poll(() => state.workflowReads).toBeGreaterThan(reads);
  const dialog = await openIncident(page);
  await dialog.getByRole('button', { name: 'Resolve incident' }).click();
  await expect(dialog.getByRole('button', { name: 'Resolved', exact: true })).toBeVisible();
  release([]);
  await page.keyboard.press('Escape');
  await expect(page.getByRole('button', { name: 'Refresh data' })).toBeEnabled();
  await expect(page.getByTestId('active-count')).toHaveText('4');
  state.workflows = [];
  await page.clock.fastForward(15_000);
  await expect.poll(() => state.workflowReads).toBeGreaterThan(reads + 1);
  await expect(page.getByTestId('active-count')).toHaveText('4');
});

test('outages retain successful data, workflow uncertainty is explicit and recovery works', async ({ page }) => {
  const state = await installApi(page);
  await openDashboard(page);
  state.mapError = 503; state.workflowError = 503;
  await page.getByRole('button', { name: 'Refresh data' }).click();
  await expect(page.getByText('Showing the last successful data.')).toBeVisible();
  await expect(page.getByText('Workflow data is stale.')).toBeVisible();
  await expect(page.getByTestId('active-count')).toHaveText('5');
  await expect(page.locator('.incident-card').first()).toContainText('Assignment unavailable');
  state.mapError = 0; state.workflowError = 0;
  await page.getByRole('button', { name: 'Retry connection' }).click();
  await expect(page.getByText('Backend connected', { exact: true })).toBeVisible();
  await expect(page.getByText('Workflow data is stale.')).toHaveCount(0);
});

test('initial failure offers explicit demo with persistent simulated actions isolated from API', async ({ page }) => {
  await installApi(page, { mapError: 503, workflowError: 404 });
  await page.goto('/');
  await expect(page.getByText('Unable to load the dashboard.')).toBeVisible();
  await expect(page.locator('.incident-card')).toHaveCount(0);
  await page.getByRole('button', { name: 'Use demo data' }).click();
  await expect(page.getByText('Local demo · simulated actions')).toBeVisible();
  await page.getByRole('button', { name: 'Operator sign in' }).click();
  const login = page.getByRole('dialog');
  await login.getByLabel('Email', { exact: true }).fill('chris@sentinelx.demo');
  await login.getByLabel('Password', { exact: true }).fill('sentinel-demo');
  await login.getByRole('button', { name: 'Sign in', exact: true }).click();
  const incident = await openIncident(page);
  await incident.getByRole('button', { name: 'Resolve incident' }).click();
  await expect(incident.getByText('Simulated change saved for this tab.')).toBeVisible();
  await page.reload();
  await page.goto('/');
  await expect(page.getByTestId('active-count')).toHaveText('4');
  await page.getByRole('button', { name: 'Connect to backend' }).click();
  await expect(page.getByText('Unable to load the dashboard.')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Operator sign in' })).toBeVisible();
});

test('empty datasets, unavailable workflows and missing evidence have honest empty states', async ({ page }) => {
  const state = await installApi(page, { workflowError: 404 });
  state.data.incidents[0].related_observation_ids = ['missing-observation'];
  await openDashboard(page);
  await expect(page.getByText('Workflow data is unavailable.')).toBeVisible();
  const dialog = await openIncident(page, 'Slow traffic on Custom House Quay');
  await expect(dialog.locator('.empty-evidence')).toContainText('Evidence unavailable');
  await expect(dialog.locator('dd').filter({ hasText: /^Unassigned$/ })).toHaveCount(0);
  await page.keyboard.press('Escape');
  state.data = { cameras: [], incidents: [], transport: [] };
  await page.getByRole('button', { name: 'Refresh data' }).click();
  await expect(page.getByText('No incidents in this dataset.')).toBeVisible();
  await expect(page.getByText('No cameras in this dataset.')).toBeVisible();
  await expect(page.getByTestId('active-count')).toHaveText('0');
});

test('broken images, unavailable map tiles and failed HLS keep snapshot inspection usable', async ({ page }) => {
  const state = await installApi(page, { tileError: true, streamUrl: 'https://video.example.test/stream.m3u8' });
  await page.route('https://video.example.test/**', (route) => route.abort());
  state.data.cameras[0].image_url = '/broken-camera.png';
  await openDashboard(page);
  await expect(page.getByText('Map tiles unavailable.', { exact: false })).toBeVisible();
  await expect(page.locator('.camera-card').first()).toContainText('Snapshot unavailable');
  await page.getByRole('button', { name: /Open camera Custom House/ }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog.locator('.detail-snapshot img')).toBeVisible();
  await dialog.getByRole('button', { name: 'Watch live video' }).click();
  await expect(dialog.getByText('Video playback failed. Showing the snapshot.')).toBeVisible({ timeout: 15_000 });
  await expect(dialog.locator('.detail-snapshot img')).toBeVisible();
});

test('mobile drawers trap focus, restore keyboard focus and do not overflow', async ({ page }) => {
  const state = await installApi(page);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await openDashboard(page);
  const opener = page.getByRole('button', { name: /Open camera Custom House/ });
  await opener.focus();
  await page.keyboard.press('Enter');
  const dialog = page.getByRole('dialog');
  await expect(dialog).toBeVisible();
  await expect(dialog.getByRole('button', { name: 'Close details' })).toBeFocused();
  await page.keyboard.press('Shift+Tab');
  expect(await dialog.evaluate((element) => element.contains(document.activeElement))).toBe(true);
  expect((await dialog.boundingBox())?.width).toBe(390);
  await page.screenshot({ path: '../output/playwright/mobile-camera.png' });
  await page.keyboard.press('Escape');
  await expect(opener).toBeFocused();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: '../output/playwright/mobile-dashboard.png', fullPage: true });
  expect(state.pageErrors).toEqual([]);
});

test('polling pauses when hidden, resumes on return, prevents overlap and times out', async ({ page }) => {
  const state = await installApi(page);
  await page.clock.install();
  await openDashboard(page);
  const initialReads = state.mapReads;
  await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, value: true }); document.dispatchEvent(new Event('visibilitychange')); });
  await page.clock.fastForward(30_000);
  expect(state.mapReads).toBe(initialReads);
  await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, value: false }); document.dispatchEvent(new Event('visibilitychange')); });
  await expect.poll(() => state.mapReads).toBe(initialReads + 1);
  await expect(page.getByRole('button', { name: 'Refresh data' })).toBeEnabled();
  let release!: (value: MapData) => void;
  state.nextMap = new Promise((resolve) => { release = resolve; });
  await page.getByRole('button', { name: 'Refresh data' }).click();
  await expect.poll(() => state.mapReads).toBe(initialReads + 2);
  await page.evaluate(() => document.dispatchEvent(new Event('visibilitychange')));
  expect(state.mapReads).toBe(initialReads + 2);
  await page.clock.fastForward(10_100);
  await page.getByRole('button', { name: 'Diagnostics' }).click();
  await expect(page.getByText('The request timed out. Please retry.', { exact: true })).toBeVisible();
  await expect(page.getByTestId('active-count')).toHaveText('5');
  release({ cameras: [], incidents: [], transport: [] });
  await expect(page.getByTestId('active-count')).toHaveText('5');
});
